### ISSUE TITLE
Main: Homeworks

### ISSUE THREAD

**Issue by thanh-guong** [vins-87/ASD-2016#1]
Nel main ci sono delle funzioni hw-1, hw-2 che non hanno reference. Che è sta roba vins?

**Comment by vins-87** [comment]
Hai provato ad includere i file
HW4-1.c
HW4-2.c
HW4-3.c
?

Il 25/gen/2017 12:23, "Falcao5" <notifications@github.com> ha scritto:

**Comment by thanh-guong** [comment]
Ma non esistono!!
