### ISSUE TITLE
Test per esame settembre 2016

### ISSUE THREAD

**Issue by thanh-guong** [vins-87/ASD-2016#2]
"Il programma ha smesso di funzionare".
Mi sembra di aver allocato tutto correttamente, e non ho idee su come risolvere..

**Comment by vins-87** [comment]
Committa e pusha così pullo e ti dico

Il 25/gen/2017 12:27, "Falcao5" <notifications@github.com> ha scritto:

**Comment by thanh-guong** [comment]
Done

**Comment by thanh-guong** [comment]
Solved
